baseURL = "http://example.org/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = "example.org"
    title = "Lucas Arroyo"
    author = "Lucas Arroyo"
    description = "WEB DEVELOPMENT STUDENT"
    copyright = "Custom copyright message"
    theme = "dark" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Lucas Arroyo"
        photo = "images/profile.jpeg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/lucas-arroyo-artiach-174a28196/"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/l-arroyo"
        title = "GitHub"

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "TECHNICIAN IN MICROCOMPUTER SYSTEMS AND NETWORKS"
        college = "CPIFP LOS ENLACES"
        website = "https://cpilosenlaces.com/"
        dates = "2019 - 2021"

        [[params.education.list]]
        degree = "HIGHER TECHNICIAN IN DEVELOPMENT OF WEB APPLICATIONS"
        college = "CPIFP LOS ENLACES"
        website = "https://cpilosenlaces.com/"
        dates = "2021 - CURRENT"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "Spanish"
        level = "Native"
        [[params.language.list]]
        language = "English"
        level = "Fluent"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

		[[params.hobbies.list]]
        interest = "Photo/Video Edition"

        [[params.hobbies.list]]
        interest = "Music Production"

        [[params.hobbies.list]]
        interest = "Social Media"

    [params.aboutme]
        description = "Spanish student currently attending my second year of a Higher Technician degree in Development of Web Applications"

    # Experiences section
    [params.experiences]
        title = "Laboral experience"

        [[params.jobs.list]]
        position = "INTERNSHIP PERIOD"
        dates = "05/04/2021 – 27/06/2021"
		link = "https://grupoaragondigital.es/"
        company = "Aragón Digital"
        details = "Software installing (operating systems, desktop applications and services), computers assembly and maintenance, ofimatic tasks and IT support."

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Awesome Project 1"
        url = "#"
        description = "Description of the *awesome* project 1"
		
		[[params.projects.list]]
        title = "Awesome Project 2"
        url = "#"
        description = "Description of the **awesome** project 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "Skill 1, Skill 2"
        skillrating = 95 # out of 100
                
        [[params.skills.list]]
        skill = "Skill 3"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "Skill 4"
        skillrating = 80